// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/info-pekanan/InfoPekanan.tsx": () => import("../components/mockups/info-pekanan/InfoPekanan.tsx"),
  "./components/mockups/tema-app/Gelap.tsx": () => import("../components/mockups/tema-app/Gelap.tsx"),
  "./components/mockups/tema-app/Indigo.tsx": () => import("../components/mockups/tema-app/Indigo.tsx"),
  "./components/mockups/tema-app/Senja.tsx": () => import("../components/mockups/tema-app/Senja.tsx"),
  "./components/mockups/tema-app/Tosca.tsx": () => import("../components/mockups/tema-app/Tosca.tsx")
};
